server:
  port: 7070
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/danielccanayucra/DAD.2024.DANIEL.git # ruta del repositorio git
          searchPaths: config-data
          default-label: practica
  security:
    user:
      name: root
      password: 123456


