server:
  port: 2711
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1027/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-category-service
          uri: lb://ms-category-service
          predicates:
            - Path=/category/**
        - id: ms-producto-service
          uri: lb://ms-producto-service
          predicates:
            - Path=/producto/**